#!/usr/bin/env python3
"""Generate dimm_fns.c and dimm_main.c: every 64-bit compare and logic operator against constants
-40..40 and some edge values, as a value (scc) and as a branch, compiled with
the constant as an immediate candidate and checked against the same operator
on a volatile copy of the constant (register operands only). GCC1 exec test for
the .d immediate fix: silicon zero-extends the imm5 of xori/ori/andi/sltiu.d."""
import sys

consts = sorted(set(list(range(-40, 41)) + [-(1 << 31), (1 << 31) - 1, 1 << 32, -(1 << 32)]))
cmp_ops = [("ltu", "<", "u64"), ("leu", "<=", "u64"), ("gtu", ">", "u64"), ("geu", ">=", "u64"),
           ("lt", "<", "s64"), ("le", "<=", "s64"), ("gt", ">", "s64"), ("ge", ">=", "s64"),
           ("eq", "==", "u64"), ("ne", "!=", "u64")]
logic_ops = [("and", "&"), ("ior", "|"), ("xor", "^")]


def cname(c):
    return ("m%d" % -c) if c < 0 else ("p%d" % c)


out = []
w = out.append
fout = []
fw = fout.append
fw("/* Generated by gen_dimm.py: the functions under test (compiled by the GCC under test). */")
fw("typedef unsigned long long u64;")
fw("typedef long long s64;")
fw("#define NI __attribute__((noinline))")
fw("volatile int sink;")
w("/* Generated by gen_dimm.py. */")
w("#include <pmsis.h>")
w("typedef unsigned long long u64;")
w("typedef long long s64;")
w("#define NI __attribute__((noinline))")
fns = []
for name, op, ty in cmp_ops:
    for c in consts:
        f = "%s_%s" % (name, cname(c))
        fw("NI int v_%s(%s x) { return x %s (%s)%dLL; }" % (f, ty, op, ty, c))
        fw("NI int b_%s(%s x) { if (x %s (%s)%dLL) { sink = 1; return 1; } return 0; }" % (f, ty, op, ty, c))
        w("int v_%s(%s x); int b_%s(%s x);" % (f, ty, f, ty))
        fns.append(("cmp", name, op, ty, c, f))
for name, op in logic_ops:
    for c in consts:
        f = "%s_%s" % (name, cname(c))
        fw("NI u64 v_%s(u64 x) { return x %s (u64)%dLL; }" % (f, op, c))
        w("u64 v_%s(u64 x);" % f)
        fns.append(("logic", name, op, "u64", c, f))

w("static const u64 xs[] = {")
xs = [0, 1, 2, 15, 16, 17, 30, 31, 32, 33, 0x7fffffff, 0x80000000, 0xffffffff, 0x100000000,
      0xfffffffffffffff0, 0xffffffffffffffef, 0xfffffffffffffff1, 0xffffffffffffffff, 0xffffffffffffffe0,
      0x8000000000000000, 0x7fffffffffffffff, 0xffffffff00000000, 0x00000001ffffffff,
      0xfffffffffffffffe, 0xffffffffffffffd8, 0x28, 0x27, 0x29]
w(",\n".join("  0x%xULL" % x for x in xs))
w("};")
w("static volatile u64 vc;")
w("static int errors, checks;")
w("static void report(const char *f, const char *kind, u64 x, u64 got, u64 want)")
w("{")
w("  checks++;")
w("  if (got != want) {")
w("    if (errors++ < 40)")
w("      printf(\"GCC1 FAIL %s %s x=%08lx%08lx got=%08lx%08lx want=%08lx%08lx\\n\", kind, f, (unsigned long)(x >> 32),")
w("             (unsigned long)x, (unsigned long)(got >> 32), (unsigned long)got, (unsigned long)(want >> 32),")
w("             (unsigned long)want);")
w("  }")
w("}")
w("int main(void)")
w("{")
w("  for (unsigned i = 0; i < sizeof(xs) / sizeof(xs[0]); i++) {")
w("    u64 x = xs[i];")
for kind, name, op, ty, c, f in fns:
    w("    vc = (u64)%dLL;" % c)
    if kind == "cmp":
        w("    { %s r = (%s)vc; int want = (%s)x %s r;" % (ty, ty, ty, op))
        w("      report(\"%s\", \"v\", x, v_%s((%s)x), want); report(\"%s\", \"b\", x, b_%s((%s)x), want); }"
          % (f, f, ty, f, f, ty))
    else:
        w("    report(\"%s\", \"v\", x, v_%s(x), x %s vc);" % (f, f, op))
w("  }")
w("  printf(\"GCC1 d-imm: %d checks, %d errors\\n\", checks, errors);")
w("  printf(\"GCC1 DONE\\n\");")
w("  return errors != 0;")
w("}")
open("dimm_main.c", "w").write("\n".join(out) + "\n")
open("dimm_fns.c", "w").write("\n".join(fout) + "\n")
